In [ ]:
import os
import pandas as pd
import kagglehub

print("1. Downloade TheLook eCommerce Datensatz...")
# Lädt den kompletten Datensatz herunter und gibt den Pfad zurück
path = kagglehub.dataset_download("mustafakeser4/looker-ecommerce-bigquery-dataset")
print("Download abgeschlossen! Die Dateien liegen unter:", path)

print("\n2. Lade Tabellen in den RAM...")


distribution_centers = pd.read_csv(os.path.join(path, "distribution_centers.csv"))
events               = pd.read_csv(os.path.join(path, "events.csv"))
inventory_items      = pd.read_csv(os.path.join(path, "inventory_items.csv"))
order_items          = pd.read_csv(os.path.join(path, "order_items.csv"))
orders               = pd.read_csv(os.path.join(path, "orders.csv"))
products             = pd.read_csv(os.path.join(path, "products.csv"))
users                = pd.read_csv(os.path.join(path, "users.csv"))

print("Datensätze wurden erfolgreich geladen!")

print("\n3. Zeilenübersicht (Kontroll-Check):")
print(f"Verteilzentren (distribution_centers): {len(distribution_centers)} Zeilen")
print(f"Events (events):                      {len(events)} Zeilen")
print(f"Inventar (inventory_items):           {len(inventory_items)} Zeilen")
print(f"Bestellpositionen (order_items):      {len(order_items)} Zeilen (Faktentabelle!)")
print(f"Bestellungen (orders):                {len(orders)} Zeilen")
print(f"Produkte (products):                  {len(products)} Zeilen")
print(f"Kunden (users):                       {len(users)} Zeilen")

/home/arcturus/miniconda3/envs/banly_project/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1. Downloade TheLook eCommerce Datensatz...
Download abgeschlossen! Die Dateien liegen unter: /home/arcturus/.cache/kagglehub/datasets/mustafakeser4/looker-ecommerce-bigquery-dataset/versions/1

2. Lade Tabellen in den RAM...
Datensätze wurden erfolgreich geladen!

3. Zeilenübersicht (Kontroll-Check):
Verteilzentren (distribution_centers): 10 Zeilen
Events (events):            2431963 Zeilen
Inventar (inventory_items):           490705 Zeilen
Bestellpositionen (order_items):      181759 Zeilen (Faktentabelle!)
Bestellungen (orders):                125226 Zeilen
Produkte (products):                  29120 Zeilen
Nutzer/Kunden (users):                100000 Zeilen

In [2]:
distribution_centers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   name       10 non-null     object
 2   latitude   10 non-null     float64
 3   longitude  10 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 448.0+ bytes

In [20]:
distribution_centers.head()

   id            name  latitude  longitude
0   1      Memphis TN   35.1174   -89.9711
1   2      Chicago IL   41.8369   -87.6847
2   3      Houston TX   29.7604   -95.3698
3   4  Los Angeles CA   34.0500  -118.2500
4   5  New Orleans LA   29.9500   -90.0667

In [4]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2431963 entries, 0 to 2431962
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   user_id          float64
 2   sequence_number  int64
 3   session_id       object
 4   created_at       object
 5   ip_address       object
 6   city             object
 7   state            object
 8   postal_code      object
 9   browser          object
 10  traffic_source   object
 11  uri              object
 12  event_type       object
dtypes: float64(1), int64(2), object(10)
memory usage: 241.2+ MB

In [5]:
events.head()

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,2198523,NaN,3,83889ed2-2adc-4b9a-af5d-154f6998e778,2021-06-17 17:30:00+00:00,138.143.9.202,São Paulo,São Paulo,02675-031,Chrome,Adwords,/cancel,cancel
1,1773216,NaN,3,7a3fc3f2-e84f-44fe-8876-eff76741f7a3,2020-08-07 08:41:00+00:00,85.114.141.79,Santa Isabel,São Paulo,07500-000,Safari,Adwords,/cancel,cancel
2,2380515,NaN,3,13d9b2fb-eee1-43fd-965c-267b38dd7125,2021-02-15 18:48:00+00:00,169.250.255.132,Mairiporã,São Paulo,07600-000,IE,Adwords,/cancel,cancel
3,2250597,NaN,3,96f1d44e-9621-463c-954c-d8deb7fffe7f,2022-03-30 10:56:00+00:00,137.25.222.160,Cajamar,São Paulo,07750-000,Chrome,Adwords,/cancel,cancel
4,1834446,NaN,3,d09dce10-a7cb-47d3-a9af-44975566fa03,2019-09-05 01:18:00+00:00,161.114.4.174,São Paulo,São Paulo,09581-680,Chrome,Email,/cancel,cancel

In [6]:
inventory_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490705 entries, 0 to 490704
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              490705 non-null  int64
 1   product_id                      490705 non-null  int64
 2   created_at                      490705 non-null  object
 3   sold_at                         181759 non-null  object
 4   cost                            490705 non-null  float64
 5   product_category                490705 non-null  object
 6   product_name                    490676 non-null  object
 7   product_brand                   490304 non-null  object
 8   product_retail_price            490705 non-null  float64
 9   product_department              490705 non-null  object
 10  product_sku                     490705 non-null  object
 11  product_distribution_center_id  490705 non-null  int64
dtypes: float64(2), int64(3), object(7)
memory usage: 44.9+ MB

In [7]:
inventory_items.head()

,id,product_id,created_at,sold_at,cost,product_category,product_name,product_brand,product_retail_price,product_department,product_sku,product_distribution_center_id
0,67971,13844,2022-07-02 07:09:20+00:00,2022-07-24 06:33:20+00:00,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
1,67972,13844,2023-12-20 03:28:00+00:00,NaN,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
2,67973,13844,2023-06-04 02:53:00+00:00,NaN,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
3,72863,13844,2021-10-16 22:58:52+00:00,2021-11-22 02:19:52+00:00,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
4,72864,13844,2021-08-07 16:33:00+00:00,NaN,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7

In [8]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181759 entries, 0 to 181758
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181759 non-null  int64
 1   order_id           181759 non-null  int64
 2   user_id            181759 non-null  int64
 3   product_id         181759 non-null  int64
 4   inventory_item_id  181759 non-null  int64
 5   status             181759 non-null  object
 6   created_at         181759 non-null  object
 7   shipped_at         118281 non-null  object
 8   delivered_at       63841 non-null   object
 9   returned_at        18232 non-null   object
 10  sale_price         181759 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 15.3+ MB

In [9]:
order_items.head()

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
0,152013,104663,83582,14235,410368,Cancelled,2023-05-07 06:08:40+00:00,NaN,NaN,NaN,0.02
1,40993,28204,22551,14235,110590,Complete,2023-03-14 03:47:21+00:00,2023-03-15 22:57:00+00:00,2023-03-18 01:08:00+00:00,NaN,0.02
2,51224,35223,28215,14235,138236,Complete,2023-12-05 13:25:30+00:00,2023-12-06 01:20:00+00:00,2023-12-10 10:04:00+00:00,NaN,0.02
3,36717,25278,20165,14235,99072,Shipped,2023-12-22 20:48:19+00:00,2023-12-24 16:44:00+00:00,NaN,NaN,0.02
4,131061,90241,71954,14235,353798,Shipped,2022-06-19 16:57:59+00:00,2022-06-19 19:29:00+00:00,NaN,NaN,0.02

In [10]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125226 entries, 0 to 125225
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      125226 non-null  int64
 1   user_id       125226 non-null  int64
 2   status        125226 non-null  object
 3   gender        125226 non-null  object
 4   created_at    125226 non-null  object
 5   returned_at   12530 non-null   object
 6   shipped_at    81461 non-null   object
 7   delivered_at  43884 non-null   object
 8   num_of_item   125226 non-null  int64
dtypes: int64(3), object(6)
memory usage: 8.6+ MB

In [11]:
orders.head()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,8,5,Cancelled,F,2022-10-20 10:03:00+00:00,NaN,NaN,NaN,3
1,60,44,Cancelled,F,2023-01-20 02:12:00+00:00,NaN,NaN,NaN,1
2,64,46,Cancelled,F,2021-12-06 09:11:00+00:00,NaN,NaN,NaN,1
3,89,65,Cancelled,F,2020-08-13 09:58:00+00:00,NaN,NaN,NaN,1
4,102,76,Cancelled,F,2023-01-17 08:17:00+00:00,NaN,NaN,NaN,2

In [12]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  object
 3   name                    29118 non-null  object
 4   brand                   29096 non-null  object
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  object
 7   sku                     29120 non-null  object
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 2.0+ MB

In [13]:
products.head()

,id,cost,category,name,brand,retail_price,department,sku,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,EBD58B8A3F1D72F4206201DA62FB1204,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,2EAC42424D12436BDD6A5B8A88480CC3,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,EE364229B2791D1EF9355708EFF0BA34,1
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women,00BD13095D06C20B11A2993CA419D16B,1
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women,F531DC20FDE20B7ADF3A73F52B71D0AF,1

In [14]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  object
 2   last_name       100000 non-null  object
 3   email           100000 non-null  object
 4   age             100000 non-null  int64
 5   gender          100000 non-null  object
 6   state           100000 non-null  object
 7   street_address  100000 non-null  object
 8   postal_code     100000 non-null  object
 9   city            99042 non-null   object
 10  country         100000 non-null  object
 11  latitude        100000 non-null  float64
 12  longitude       100000 non-null  float64
 13  traffic_source  100000 non-null  object
 14  created_at      100000 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 11.4+ MB

In [15]:
users.head()

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at
0,457,Timothy,Bush,timothybush@example.net,65,M,Acre,87620 Johnson Hills,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2022-07-19 13:51:00+00:00
1,6578,Elizabeth,Martinez,elizabethmartinez@example.com,34,F,Acre,1705 Nielsen Land,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2023-11-08 18:49:00+00:00
2,36280,Christopher,Mendoza,christophermendoza@example.net,13,M,Acre,125 Turner Isle Apt. 264,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Email,2019-08-24 06:10:00+00:00
3,60193,Jimmy,Conner,jimmyconner@example.com,64,M,Acre,0966 Jose Branch Apt. 008,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2020-02-15 11:26:00+00:00
4,64231,Natasha,Wilson,natashawilson@example.net,25,F,Acre,20798 Phillip Trail Apt. 392,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2020-03-13 06:45:00+00:00